### ISSUE TITLE
fix: 审计中心回调 Job 获取资源实例 schema 报错

### ISSUE THREAD

**Issue by wangyu096** [TencentBlueKing/bk-job#2541]
**Version / Branch / tag**
 3.8.3

**出了什么问题？(What Happened?)**

审计中心回调 Job 获取资源实例 schema 报错。报错日志：
```
Caused by: java.lang.Exception: Fail to execute logBeforeProcessCallbackRequest
        at com.tencent.bk.job.common.iam.aspect.IamCallbackAspect.logBeforeProcessCallbackRequest(IamCallbackAspect.java:48)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:634)
        at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:624)
        at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:72)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        ... 70 common frames omitted
Caused by: java.lang.ExceptionInInitializerError: null
        at com.tencent.bk.job.manage.api.iam.impl.IamTaskPlanCallbackResourceImpl.fetchResourceTypeSchemaResp(IamTaskPlanCallbackResourceImpl.java:205)
        at com.tencent.bk.job.common.iam.service.BaseIamCallbackService.baseCallback(BaseIamCallbackService.java:137)
        at com.tencent.bk.job.manage.api.iam.impl.IamTaskPlanCallbackResourceImpl.callback(IamTaskPlanCallbackResourceImpl.java:198)
        at com.tencent.bk.job.manage.api.iam.impl.IamTaskPlanCallbackResourceImpl$$FastClassBySpringCGLIB$$3e51bd5e.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
        at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89)
        at com.tencent.bk.job.common.iam.aspect.IamCallbackAspect.logBeforeProcessCallbackRequest(IamCallbackAspect.java:46)
        ... 79 common frames omitted
Caused by: java.lang.NullPointerException: null
        at com.fasterxml.jackson.module.jsonSchema.JsonSchemaGenerator.<init>(JsonSchemaGenerator.java:38)
        at com.fasterxml.jackson.module.jsonSchema.JsonSchemaGenerator.<init>(JsonSchemaGenerator.java:33)
        at com.tencent.bk.audit.utils.json.JsonSchemaUtils.<clinit>(JsonSchemaUtils.java:14)
        ... 89 common frames omitted
```

**Comment by wangyu096** [comment]
bug分析：

审计 SDK bug 导致，见 https://github.com/TencentBlueKing/bk-audit-java-sdk/issues/9
