### ISSUE TITLE
bugfix: 作业执行过程中DB出现问题，导致任务状态一直为”正在执行"

### ISSUE THREAD

**Issue by wangyu096** [TencentBlueKing/bk-job#654]
**版本/分支/tag**
3.4.4
**问题描述**
```
[2022-02-15 08:44:39.118] ERROR [,334bed3d18547f6a,7470844b9cc4f4a1] 29866 --- [task-result-handle-36614] c.t.b.j.e.e.r.AbstractResultHandleTask : [20035709634]: result handle error. org.jooq.exception.DataAccessException: Error getting connection from data source HikariDataSource (job-execute) at org.jooq_3.14.8.MYSQL.debug(Unknown Source) at org.jooq.impl.DataSourceConnectionProvider.acquire(DataSourceConnectionProvider.java:90) at org.jooq.impl.DefaultExecuteContext.connection(DefaultExecuteContext.java:649) at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:338) at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:481) at org.jooq.impl.AbstractResultQuery.fetchLazy(AbstractResultQuery.java:450) at org.jooq.impl.AbstractResultQuery.fetchLazyNonAutoClosing(AbstractResultQuery.java:464) at org.jooq.impl.AbstractResultQuery.fetchOne(AbstractResultQuery.java:641) at org.jooq.impl.SelectImpl.fetchOne(SelectImpl.java:3074) at com.tencent.bk.job.execute.dao.impl.StepInstanceDAOImpl.getStepInstanceBase(StepInstanceDAOImpl.java:317) at com.tencent.bk.job.execute.dao.impl.StepInstanceDAOImpl$$FastClassBySpringCGLIB$$28a83a58.invoke(<generated>) at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692) at com.tencent.bk.job.execute.dao.impl.StepInstanceDAOImpl$$EnhancerBySpringCGLIB$$7d708db0.getStepInstanceBase(<generated>) at com.tencent.bk.job.execute.service.impl.TaskInstanceServiceImpl.getBaseStepInstance(TaskInstanceServiceImpl.java:151) at com.tencent.bk.job.execute.engine.result.AbstractResultHandleTask.shouldSkipStep(AbstractResultHandleTask.java:368) at com.tencent.bk.job.execute.engine.result.AbstractResultHandleTask.execute(AbstractResultHandleTask.java:277) at com.tencent.bk.job.execute.engine.result.ScheduledContinuousResultHandleTask.executeTask(ScheduledContinuousResultHandleTask.java:166) at com.tencent.bk.job.execute.engine.result.ScheduledContinuousResultHandleTask.execute(ScheduledContinuousResultHandleTask.java:119) at com.tencent.bk.job.execute.engine.result.ResultHandleManager$TaskWorker.loop(ResultHandleManager.java:445) at com.tencent.bk.job.execute.engine.result.ResultHandleManager$TaskWorker.run(ResultHandleManager.java:422) at java.lang.Thread.run(Thread.java:748) Caused by: java.sql.SQLTransientConnectionException: job-execute - Connection is not available, request timed out after 30000ms. at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:695) at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:197) at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:162) at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128) at sun.reflect.GeneratedMethodAccessor174.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344) at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:137) at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:124) at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:215) at com.sun.proxy.$Proxy166.getConnection(Unknown Source) at org.jooq.impl.DataSourceConnectionProvider.acquire(DataSourceConnectionProvider.java:87) ... 26 common frames omitted
```
**如何复现**
DB连接异常即可复现
**预期结果**
即使DB连接异常，任务状态设置为“任务异常”或者有某种重试机制

**Comment by wangyu096** [comment]
已修复
